### PR TITLE
Bumping to k8s 1.26 and controller-runtime 0.14.1

### PR DESCRIPTION
**Pull request by tiraboschi**
**Description of the change:**
* Bumping to k8s v1.26
* Bumping to controller-runtime v0.14.1
* Update tests to Ginkgo v2

**Motivation for the change:**
Consume up-to-date dependencies

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

### CODE REVIEW

**Review by joelanford — APPROVED** [review]

**Comment by joelanford** [comment]
Thanks @tiraboschi!

**Comment by tiraboschi** [comment]
ping

**Comment by tiraboschi** [comment]
@joelanford ping

**Pull request merged**
