### PR TITLE
Bumping to k8s 1.25

### PR DESCRIPTION
**Pull request by jmrodri**
**Description of the change:**

Bumping to k8s v1.25

**Motivation for the change:**

### CODE REVIEW

**Comment by jmrodri** [comment]
In the process of updating k8s to 1.25, we had to bump go to 1.19. That resulted in also bumping golangci-lint to 1.49 and fixing the github action. This PR is currently blocked by the prow test all call, that was configured for go 1.17 which I bumped to 1.19 right now. Blocked by https://github.com/openshift/release/pull/31977

**Review by asmacdo — APPROVED** [review]
/lgtm

**Comment by jmrodri** [comment]
As of go 1.19 `ioutil` has been deprecated. They introduced the same functionality in `os` starting in go 1.16. https://pkg.go.dev/io/ioutil@go1.19.1

**Pull request merged**
